name = "Sqids"
uuid = "5846b9ac-096c-425b-b363-8d1a03210e20"
authors = ["GOTOH Shunsuke <antimon2.me@gmail.com> and contributors"]
version = "0.1.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
